-   id: dprint
    name: dprint
    entry: dprint fmt
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["dprint@0.18.2"]
    minimum_pre_commit_version: '0'
    description: 'A pluggable and configurable code formatting platform written in Rust.'
